title: DI Kevin Feichtinger, BSc
description:  The CV of DI Kevin Feichtinger, BSc
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
