title: DI Dr. Kevin Feichtinger, BSc
description:  The CV of DI Dr. Kevin Feichtinger, BSc
url: https://cv.kevin-feichtinger.at
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
