title: DI Kevin Feichtinger, BSc
description:  The CV of DI Kevin Feichtinger, BSc
url: https://cv.kevin-feichtinger.com
baseurl: 'https://cv.kevin-feichtinger.com'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
